/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Connect;

import java.awt.Color;
import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Timer timer;
    int h, m, s;
    Boolean flag =true;

    public NewJFrame() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbnap = new javax.swing.JLabel();
        btnap = new javax.swing.JButton();
        txtnap = new javax.swing.JTextField();
        bnstop = new javax.swing.JButton();
        lbh = new javax.swing.JLabel();
        lbm = new javax.swing.JLabel();
        lbs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("time còn lại");

        lbnap.setText("jLabel3");

        btnap.setText("jButton1");
        btnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapActionPerformed(evt);
            }
        });

        txtnap.setText("jTextField1");

        bnstop.setText("stop");

        lbh.setText("jLabel1");

        lbm.setText("jLabel3");

        lbs.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(lbnap)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnap))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lbh)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bnstop))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lbm)))
                        .addGap(18, 18, 18)
                        .addComponent(lbs)
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbm)
                            .addComponent(lbs))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnap)
                            .addComponent(bnstop)))
                    .addComponent(lbh))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapActionPerformed
        
        String naptien;
        naptien = txtnap.getText();
        int nap;
        nap = Integer.parseInt(naptien);
        lbnap.setText(naptien);
        int thoigian;
        thoigian = nap / 6;
        h = thoigian/3600;
        m = thoigian %3600 /60;
        s = thoigian %3600/60;
        

        timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                while(s>=60){
                    s-=60;
                    m++;
                }
                if(m == 0){
                    lbm.setForeground(Color.red);
                    lbs.setForeground(Color.red);
                    
                }
                if(s ==0){
                    s=60;
                    m --;
                }
                if(m <0){
                    JOptionPane.showMessageDialog(rootPane, "run of time");
                    m = 0;
                    s= 0;
                    timer.stop();
                }else{
                    s--;
                    if(s<10){
                        lbs.setText("0" + s);
                        flag = false;
                    }else if(s >= 10 && s <=60){
                        lbs.setText("" + s);
                    }
                    if(m <10){
                        lbm.setText("0" + m);
                        if(s<10){
                            lbs.setText("0" + s);
                        }else{
                        lbs.setText("" + s);
                        }
                        flag = false; 
                 }else if(m >= 10 && m <=60){
                        lbm.setText("" + m);
                         if(s <10){
                             lbs.setText("0" + s);
                         }else{
                             lbs.setText("" + s);
                    }
                    }
                    if(h <10){
                        lbh.setText("0" + h);
                        if(m<10){
                            lbs.setText("0" + m);
                        }else{
                        lbm.setText("" + m);
                        }
                        flag = false; 
                 }else if(h >= 10 && h <=60){
                        lbh.setText("" + h);
                         if(m <10){
                             lbm.setText("0" + m);
                         }else{
                             lbm.setText("" + m);
                    }
                    }
                    
                    if(flag){
                        lbm.setText("" + m);
                        lbs.setText("" + s);
                    }
            }  
         }//To change body of generated methods, choose Tools | Templates.

           
            
        });
        if(s>0)
            timer.start();
          
    }//GEN-LAST:event_btnapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnstop;
    private javax.swing.JButton btnap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbh;
    private javax.swing.JLabel lbm;
    private javax.swing.JLabel lbnap;
    private javax.swing.JLabel lbs;
    private javax.swing.JTextField txtnap;
    // End of variables declaration//GEN-END:variables
}
